#!/usr/bin/env node

/**
 * WriteFlow AI - Setup Script
 *
 * This script helps you configure your WriteFlow AI platform.
 * Run with: node scripts/setup.js
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')
const crypto = require('crypto')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

const question = (query) => new Promise((resolve) => rl.question(query, resolve))

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║              WriteFlow AI - Setup Wizard                      ║
║                                                               ║
║  This wizard will help you configure your AI writing          ║
║  platform. You'll need:                                       ║
║                                                               ║
║  1. A PostgreSQL database URL (free from Neon or Supabase)    ║
║  2. An OpenAI API key (from platform.openai.com)              ║
║  3. Stripe API keys (from dashboard.stripe.com)               ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`)

async function main() {
  try {
    // Check if .env already exists
    const envPath = path.join(__dirname, '..', '.env')
    if (fs.existsSync(envPath)) {
      const overwrite = await question('\n.env file already exists. Overwrite? (y/N): ')
      if (overwrite.toLowerCase() !== 'y') {
        console.log('\nSetup cancelled. Your existing .env file was preserved.')
        rl.close()
        return
      }
    }

    console.log('\n📚 Step 1/4: Database Configuration\n')
    console.log('Get a free PostgreSQL database from:')
    console.log('  - Neon: https://neon.tech (recommended)')
    console.log('  - Supabase: https://supabase.com')
    console.log('  - Railway: https://railway.app\n')

    const databaseUrl = await question('Enter your DATABASE_URL: ')

    if (!databaseUrl || !databaseUrl.includes('postgresql')) {
      console.log('\n⚠️  Warning: DATABASE_URL should start with "postgresql://"')
    }

    console.log('\n🤖 Step 2/4: OpenAI Configuration\n')
    console.log('Get your API key from: https://platform.openai.com/api-keys\n')

    const openaiKey = await question('Enter your OPENAI_API_KEY: ')

    console.log('\n💳 Step 3/4: Stripe Configuration\n')
    console.log('Get your API keys from: https://dashboard.stripe.com/apikeys')
    console.log('(Use test keys for development, live keys for production)\n')

    const stripeSecretKey = await question('Enter your STRIPE_SECRET_KEY (sk_...): ')
    const stripePublishableKey = await question('Enter your STRIPE_PUBLISHABLE_KEY (pk_...): ')

    console.log('\nNow create a product and price in Stripe:')
    console.log('1. Go to https://dashboard.stripe.com/products')
    console.log('2. Click "Add product"')
    console.log('3. Name: "WriteFlow Pro", Price: $9.99/month, Recurring')
    console.log('4. Copy the Price ID (starts with price_)\n')

    const stripePriceId = await question('Enter your STRIPE_PRICE_ID (price_...): ')

    console.log('\n🌐 Step 4/4: App URL\n')
    console.log('For local development, use: http://localhost:3000')
    console.log('For production, use your deployed URL (e.g., https://your-app.vercel.app)\n')

    let appUrl = await question('Enter your APP_URL (default: http://localhost:3000): ')
    if (!appUrl) appUrl = 'http://localhost:3000'

    // Generate JWT secret
    const jwtSecret = crypto.randomBytes(32).toString('hex')

    // Create .env file
    const envContent = `# WriteFlow AI Configuration
# Generated by setup script on ${new Date().toISOString()}

# Database (PostgreSQL)
DATABASE_URL="${databaseUrl}"

# JWT Secret (auto-generated)
JWT_SECRET="${jwtSecret}"

# OpenAI
OPENAI_API_KEY="${openaiKey}"

# Stripe
STRIPE_SECRET_KEY="${stripeSecretKey}"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${stripePublishableKey}"
STRIPE_PRICE_ID="${stripePriceId}"
STRIPE_WEBHOOK_SECRET="whsec_placeholder"

# App URL
NEXT_PUBLIC_APP_URL="${appUrl}"
`

    fs.writeFileSync(envPath, envContent)

    console.log('\n✅ Configuration saved to .env file!')
    console.log('\n📋 Next steps:\n')
    console.log('1. Install dependencies:')
    console.log('   npm install\n')
    console.log('2. Initialize the database:')
    console.log('   npx prisma db push\n')
    console.log('3. Start the development server:')
    console.log('   npm run dev\n')
    console.log('4. Open http://localhost:3000 in your browser\n')
    console.log('5. For Stripe webhooks (required for subscriptions):')
    console.log('   - Install Stripe CLI: https://stripe.com/docs/stripe-cli')
    console.log('   - Run: stripe listen --forward-to localhost:3000/api/stripe/webhook')
    console.log('   - Copy the webhook signing secret to STRIPE_WEBHOOK_SECRET in .env\n')
    console.log('═══════════════════════════════════════════════════════════════')
    console.log('🎉 Setup complete! Your AI writing platform is ready to launch.')
    console.log('═══════════════════════════════════════════════════════════════\n')

  } catch (error) {
    console.error('\n❌ Error during setup:', error.message)
  } finally {
    rl.close()
  }
}

main()
